# Generated by Django 5.2.3 on 2025-11-28 14:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('category_type', models.CharField(choices=[('public', 'Public Holiday'), ('religious', 'Religious'), ('international', 'International'), ('fun', 'Fun/Quirky'), ('seasonal', 'Seasonal')], max_length=20)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Holiday Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('year', models.IntegerField(db_index=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_global', models.BooleanField(default=False)),
                ('is_public_holiday', models.BooleanField(default=False)),
                ('is_bank_holiday', models.BooleanField(default=False)),
                ('is_observance', models.BooleanField(default=False)),
                ('is_lunar', models.BooleanField(default=False)),
                ('lunar_date', models.CharField(blank=True, max_length=50)),
                ('sources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('wikipedia_url', models.URLField(blank=True)),
                ('official_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='holidays', to='holidays.country')),
                ('categories', models.ManyToManyField(related_name='holidays', to='holidays.holidaycategory')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=10)),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='holidays.holiday')),
            ],
            options={
                'verbose_name_plural': 'Holiday Aliases',
                'unique_together': {('holiday', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date', 'is_global'], name='holidays_ho_date_3092ea_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['year', 'date'], name='holidays_ho_year_cd24cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together={('name', 'date', 'year')},
        ),
    ]
